Added onboarding form
SephoraUniverse/sephora-microsite pull request #35
Opened 2023-05-01 21:31 UTC by ayanb12

2023-05-02 09:12 UTC, robinsingh1912 commented
@ayanb12  can you please resolve the above conflicts first

2023-05-03 12:49 UTC, ayanb12 commented
> 

Yes working on it

2023-05-03 20:02 UTC, theisens approved these changes

2023-05-03 20:15 UTC, robinsingh1912 requested changes

2023-05-03 20:15 UTC, robinsingh1912 commented on src/components/Checkbox.jsx
> +          {...register(id, {
Please add and Use zod for input validation

2023-05-03 20:15 UTC, robinsingh1912 commented on src/components/OnboardingForm.jsx
> +              {...register('nickname', {
Zod resolver here too with react hook form

2023-05-04 13:34 UTC, ayanb12 commented on src/components/OnboardingForm.jsx
> +              {...register('nickname', {
Added

2023-05-04 13:34 UTC, ayanb12 commented on src/components/Checkbox.jsx
> +          {...register(id, {
Added

2023-05-04 14:00 UTC, robinsingh1912 requested changes

2023-05-04 15:40 UTC, ayanb12 commented on src/components/NavBar.jsx
> +
Removed the nested parameters

2023-05-04 15:41 UTC, ayanb12 commented on src/components/NavBar.jsx
> +          logout={logout}
corrected used from useAuth

2023-05-04 19:55 UTC, robinsingh1912 requested changes

2023-05-04 19:55 UTC, robinsingh1912 commented on src/components/DropdownInput.jsx
> +export default function DropdownInput(props) {
should destructure the props

2023-05-04 19:55 UTC, robinsingh1912 commented on src/hooks/useValidations.js
> +export default useValidations;
No need to create a hook If your helper function does not require any React hooks, then you do not need to create a custom hook. A simple utility function or helper function would sufficient.

2023-05-04 20:03 UTC, robinsingh1912 commented on src/components/Forms/Controller/Controller.jsx
> +};
import { useForm, Controller } from "react-hook-form";
 and i guess no need to create create a component we can directly import it

2023-05-04 20:22 UTC, ayanb12 commented on src/components/Forms/Controller/Controller.jsx
> +};
Okay Got it

2023-05-04 20:25 UTC, ayanb12 commented on src/hooks/useValidations.js
> +export default useValidations;
Okay moving the logic to utils

2023-05-04 20:39 UTC, robinsingh1912 approved these changes

2023-05-04 21:52 UTC, merged